name: "CI"

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno check *.ts
      - run: deno lint *.ts
      - run: deno fmt --check
